version: 2
jobs:
  test:
    docker:
      - image: circleci/ruby:2.6.0-node-browsers
      - image: circleci/mongo:latest
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - restore_cache:
          keys:
            - bundle-{{ checksum "Gemfile.lock" }}
            - bundle-
      - run:
          name: Install abstract_type
          command: gem install abstract_type
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      - save_cache:
          key: bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:27017 -timeout 1m
      - run:
          name: Test
          command: bundle exec rake

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
