# 不要なRDocは書いていない
Style/Documentation:
  Enabled: false

# 日本語のコメントを許可する
Style/AsciiComments:
  Enabled: false

# 1行目にあわせる
Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

# 引数で渡す場合など、Hashのbracesは、ずれてもよい。
Layout/IndentHash:
  Enabled: false

# 1行目にあわせる
Layout/IndentArray:
  EnforcedStyle: consistent

# テーブル形式にそろえる
Layout/AlignHash:
  EnforcedColonStyle: table

# 明示的にメソッドを指定した方がわかりやすい場合もある。
Style/SymbolProc:
  Enabled: false

# compact スタイルを使うが、 module を定義するところだけ、
# 冗長なのでnested スタイルにしている。
Style/ClassAndModuleChildren:
  Enabled: false

# 継承元では引数を使わない場合はある
Lint/UnusedMethodArgument:
  Enabled: false

# class body の前後に改行を挿入する。
Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

# 条件or処理が長い場合、if-endを使いたい。
Style/GuardClause:
  Enabled: false

# Hashのフォーマットに影響するので、処理しない
Style/BracesAroundHashParameters:
  Enabled: false

Style/ClassVars:
  Enabled: false

# 引数は8個までOK
Metrics/ParameterLists:
  Max: 8
  CountKeywordArgs: false

# 別名にマッピングしたい場合がある
Style/TrivialAccessors:
  ExactNameMatch:	true

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Layout/MultilineMethodDefinitionBraceLayout:
  Enabled: false

Style/IfInsideElse:
  Enabled: false

Metrics/ModuleLength:
  Max: 200

Style/MultilineTernaryOperator:
  Enabled: false
